### PR TITLE
Use the fs block size for chunks if larger than 64 kb

### PR DESCRIPTION
**Pull request by lnicola**
See https://github.com/seanmonstar/futures-fs/issues/3 for the reasoning.

Although I recently realized that's a pessimization for more common block sizes like 4 KB.

### CODE REVIEW

**Comment by scottlamb** [comment]
Where does this make a difference in practice? I just checked my HFS filesystem on macOS and an ext4 filesystem on Linux; both reported 4 KiB blocks.

**Comment by lnicola** [comment]
My tests in the `futures-fs` PR were made on ZFS.

**Comment by scottlamb** [comment]
Oh, you said that in the link, but I missed it.

Hmm. I'm not real excited about this change for a few reasons:

   * I'm not sure 128 KiB chunks would be faster even for you. The linked benchmark was with different code and didn't consider the chunk size http-serve currently uses. Maybe 64 KiB is the sweet spot. I'd want a benchmark showing 128 KiB vs 64 KiB (and perhaps other sizes) with this code.
   * Even if 128 KiB chunks are faster, I'm not sure it's worth the extra memory usage (particularly if there are many simultaneous clients, so a large multiplier). If anything, I think people might want to turn down the chunk size. 168MB/s is already quite fast. Why do you care if it could be a little faster, considering that there's a tradeoff involved?
   * I'm not sure the chunk size should match the filesystem block size. I.e., if 128 KiB chunks are better, would they also be better even on filesystems with 4 KiB blocks? I don't see much importance to matching that number, especially when the data is hot in cache (as it likely was in your benchmark). And if it's not in cache, we might get more improvement from using readahead (as this code did prior to c09444e) than from making larger reads. Larger reads might even be worse; if we have the next 4 KiB available in cache, better to get those in flight before hitting disk for more.

I'd be more inclined to just make this tunable, leaving the filesystem block size out of it.

**Comment by lnicola** [comment]
I think it's best to postpone this for a while (and maybe investigate `tokio-fs`).

**Pull request closed without merging**
